/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/32-medpoly-anim-gltfjsx.glb");
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="capTop"
					castShadow
					receiveShadow
					geometry={nodes.capTop.geometry}
					material={materials.cap}
					position={[0, 0.213, -0.033]}
				/>
				<mesh name="bottle" castShadow receiveShadow geometry={nodes.bottle.geometry} material={materials.bottle} />
				<mesh
					name="button"
					castShadow
					receiveShadow
					geometry={nodes.button.geometry}
					material={materials.button}
					position={[0, 0.212, 0.03]}
				/>
				<mesh
					name="capBottom"
					castShadow
					receiveShadow
					geometry={nodes.capBottom.geometry}
					material={materials.cap}
					position={[0, 0.191, 0]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/models/32-medpoly-anim-gltfjsx.glb");
